### ISSUE TITLE
npm run lint causes `Unnecessary escape character` error on eslint

### ISSUE THREAD

**Issue by jdcargile** [singingwolfboy/create-linked-clubhouse-story#11]
Steps to reproduce:
1. Pull down repo.
2. Run `npm install`
3. Run `npm lint`
4. You receive the following error.
```
./create-linked-clubhouse-story/src/util.ts
16:54  error  Unnecessary escape character: \/  no-useless-escape
16:71  error  Unnecessary escape character: \/  no-useless-escape
```

**Comment by singingwolfboy** [comment]
Thanks for reporting that! Resolved by https://github.com/singingwolfboy/create-linked-clubhouse-story/commit/8404f18562543a7543aa2a2934bf912fadb9b384
