### ISSUE TITLE
New release for Only Users feature

### ISSUE THREAD

**Issue by jdcargile** [singingwolfboy/create-linked-clubhouse-story#8]
@singingwolfboy, I am very excited to get my PR merged for the Only Users feature, but I am unable to use it from your repo in GH Actions until you have a new release up. Can you please create a new release?

**Comment by singingwolfboy** [comment]
You can always depend on the `main` branch instead of a tagged release. I plan to release a new version once #10 is merged.

**Comment by jdcargile** [comment]
Thank you. I will take that approach until you make a new release.

**Comment by singingwolfboy** [comment]
I just created the `v1.6` tag, which has #6 and #10 in it. Thank you so much for contributing these features! 🎉
